### ISSUE TITLE
 Running Lua scripts. Mandatory tag Cache-Control: no-cache

### ISSUE THREAD

**Issue by devspbniif** [marcelvanherk/Conquest-DICOM-Server#11]
![Screenshot_1](https://user-images.githubusercontent.com/69792605/104706244-e6a95780-572b-11eb-86d3-af2bf49c2c60.png)

![Screenshot_2](https://user-images.githubusercontent.com/69792605/104706262-ead57500-572b-11eb-9e81-469d94716689.png)

![Screenshot_3](https://user-images.githubusercontent.com/69792605/104706272-ed37cf00-572b-11eb-98b6-6836d05620b6.png)

![Screenshot_4](https://user-images.githubusercontent.com/69792605/104706279-ef9a2900-572b-11eb-8197-df7662405719.png)

![Screenshot_5](https://user-images.githubusercontent.com/69792605/104706292-f1fc8300-572b-11eb-924a-9657e8aa6806.png)

That is how it should be?

**Comment by marcelvanherk** [comment]
Hi,

I think your header = entry should end with a \ which means a newline there.
E.g.

header = Content-Type: application/x-java-jnlp-file\

Then it will likely work without the extra print statement.

Marcel

**Comment by marcelvanherk** [comment]
Nowadays I mostly write the header from the script.

**Comment by devspbniif** [comment]
Hi!
Thanks for the answer!
but, this is how it works: `header = Content-Type: application/json\Access-Control-Allow-Origin: *` - two headers
doesn't work like that: `header = Content-Type: application/json\Cache-Control: no-cache` or `header = Content-Type: application/json\Cache-Control: no-cache\Access-Control-Allow-Origin: *`

**Comment by marcelvanherk** [comment]
Best write the header from your script and not use the header ini entry for
simplicity,

Marcel

**Comment by marcelvanherk** [comment]
Closed as config issue in outdated option
