### ISSUE TITLE
Unknown Can't send images....

### ISSUE THREAD

**Issue by Blupanthr2** [marcelvanherk/Conquest-DICOM-Server#15]
Using 1.5.0b on Ubuntu Linux 20.04.3, I am able to send to 3/4 Destinations.  Destination AET1, I have a DICOM echo (--echo:AET) and I can send from KPACS to it, but conquest hangs at:
conquest-server[195430]: Queue: retrying processing of file /storage/DICOM/16497242310000.dcm
conquest-server[195430]: ExportConverter0.0: forward /storage/DICOM/16497242310000.dcm to AET1

It worked during testing 2 weeks ago, and now doesn't.  I tried re-compiling dgate in case a system update caused an issue.  It still sends fine to all other destinations, except this one.  Destination AET1 & AET2 are DCM4CHEE.
A Twin proxy at a different location is set exactly the same, and works without issues.  I've tried upping the debug level, but all it shows me is memory updates.  What can I do to get this resolved?

dicom.ini:
[Basically Default]
...
ForwardAssociationLevel           = PATIENT
ForwardAssociationCloseDelay      = 5
ForwardAssociationRefreshDelay    = 3600
ForwardAssociationRelease         = 1

FailHoldOff                       = 15
RetryDelay                        = 30
RetryForwardFailed                = 1
RetryForwardRemoteDICOMError      = 1
QueueSize                         = 128000
ForwardCollectDelay               = 60
MaximumExportRetries              = 0
MaximumDelayedFetchForwardRetries = 0

ExportConverters        = 2
ExportConverter0        = forward to AET1
ExportConverter1        = forward to AET2

**Comment by marcelvanherk** [comment]
Hi,

is this resolved on the forum?

Marcel

**Comment by Blupanthr2** [comment]
Still running on a Temporary fix, we changed the AET of the receiving station AET1, and it started working... Never did find out what the root cause was.

**Comment by marcelvanherk** [comment]
Did you put the AE below e.g V* ?

**Comment by marcelvanherk** [comment]
Closed due to inactivity
