### ISSUE TITLE
MRI SPECTOCOPY Images not receiving 

### ISSUE THREAD

**Issue by arunjoshtech** [marcelvanherk/Conquest-DICOM-Server#31]
Conquest server not receiving spectroscopy images send from MRI. is there any special settings in conquest to enable it?

**Comment by marcelvanherk** [comment]
Hi,

you need to add the sopclass to dgatesop.lst, and enable jpeg support.

Marcel

**Comment by arunjoshtech** [comment]
Hi,
I am new to conquest, is it possible to guide it step by step? I am much confused and failed many times.

**Comment by marcelvanherk** [comment]
Edit dgatesop.lst 

Remove at least the # before lines with 1.2.840.1008.1.2.1 and 1.2.840.1008.1.2.2, Look into the DICOM file for SOPClassUID (looks like 1.2.840.10008.5.1.4.1.1.4.2), and add a line like:

MyMRSpectroscopyStorage                                1.2.840.10008.5.1.4.1.1.4.2		sop

To it. Then restart conquest.

Marcel

**Comment by arunjoshtech** [comment]
It was modality side image type issues, since it got resolved. they need to save file as DCOM before they transfer the Spectroscopy Image.
Thanks for your reply and support.

**Comment by marcelvanherk** [comment]
Closed as not a Conquest issue
