### ISSUE TITLE
Wildcards in ACRNEMA Map

### ISSUE THREAD

**Issue by marcdidom** [marcelvanherk/Conquest-DICOM-Server#32]
I'm trying to allow any application to retrieve from Conquest without listing it in the map.  Is there a way to enable that feature using wildcards like so?
`*			*		*		un`

**Comment by marcelvanherk** [comment]
Yes, you use e.g V192.168.1.101 as AE title. In acrnema.map entry v* * 1234
un will then return connection to 192.168.1.101.

**Comment by marcdidom** [comment]
That works for C-Find but doesn't transfer the files on the C-Get request.

**Comment by marcelvanherk** [comment]
Hi C-GET was broken in 1.5.0c, is fixed in 1.5.0d

**Comment by marcelvanherk** [comment]
This should all be good now
