### ISSUE TITLE
Where is possible to get compiled server? Link does not work

### ISSUE THREAD

**Issue by Makhaon** [marcelvanherk/Conquest-DICOM-Server#33]
Hi, this link returned 404 for me:
http://ingenium.home.xs4all.nl/dicomserver/dicomserver150c.zip
Does it possible to get this version in the some another link?

**Comment by robertvanommen** [comment]
http://www.natura-ingenium.nl/dicomserver/dicomserver150c.zip

**Comment by marcelvanherk** [comment]
The links should be OK now
