### ISSUE TITLE
retrieval study 

### ISSUE THREAD

**Issue by HospitalFossati** [marcelvanherk/Conquest-DICOM-Server#34]
Hello, I have been using Conquest DICOM for some time now, and now version 1.5.0d as a PACS for 'RX' and 'MG', and I am very satisfied with it. This week, we incorporated a new 'C-arc' equipment that produces 'XA' modality, and I have been able to send images to Conquest without any issues. However, when I try to retrieve 'RX' images of the patients, I receive the complete list of their studies, but it doesn't allow me to perform the 'retrieval' operation towards the 'C-arc'. I also tried the same with Orthanc, regarding the retrieval, and I am experiencing the same problem. Can you help me figure out 'where' and 'what' I need to configure? Thank you very much.

**Comment by marcelvanherk** [comment]
Hi,

Is conquest registereded with C-arc as storage user? Or is it a firewall
issue? Retrieval reverses the connection.

Marcel

**Comment by marcelvanherk** [comment]
Closing as does not seem to be a Conquest issue
