### ISSUE TITLE
PhotometricInterpretation in To8bitMonochromeOrRGB

### ISSUE THREAD

**Issue by lncoll** [marcelvanherk/Conquest-DICOM-Server#38]
In function To8bitMonochromeOrRGB no PhotometricInterpretation is checked for mochrome images.
I have modified the function, but cant pull a new branch. Permission is denied for me.
How can I send it to you?

**Comment by marcelvanherk** [comment]
Hi,

you can mail it to me on ***@***.***

Thanks

Marcel

**Comment by lncoll** [comment]
Hi,
Too safe email :D
This are my first days in github. So learning it.
Attached you have the file modified.
Changes marked as lncoll.
Hope is useful for you.

[nkiqrsop.zip](https://github.com/marcelvanherk/Conquest-DICOM-Server/files/14727360/nkiqrsop.zip)

**Comment by marcelvanherk** [comment]
Hi,

your code has been integrated on Git:

https://github.com/marcelvanherk/Conquest-DICOM-Server

Can you give it a try?

Marcel

**Comment by lncoll** [comment]
Hi,
Tested in Linux. It works perfect.
Here you have a MONOCHROME1 image, finally with the correct lut.

Luis.

![Captura desde 2024-03-29 23-57-31](https://github.com/marcelvanherk/Conquest-DICOM-Server/assets/11807036/7b1f2b00-ba98-4cd7-88d0-72085d846a6f)
