### ISSUE TITLE
WadoSeriesViewer fails sometimes getting WindowWidth and WindowCenter.

### ISSUE THREAD

**Issue by lncoll** [marcelvanherk/Conquest-DICOM-Server#39]
Hi,
I've noticed in wadoseriesviewer, windowwidth and windowcenter is set to 1000 when this info is not at the dicom object.
Here I send you a proposal to correct this.
Changes marked as lncoll.
Hope is useful.
Luis
[wadoseriesviewer.zip](https://github.com/marcelvanherk/Conquest-DICOM-Server/files/14812889/wadoseriesviewer.zip)

**Comment by marcelvanherk** [comment]
Hi Luis,

I have merged it. Not sure why I was testing on empty string, but let's see
if this breaks somewhere.

Marcel

**Comment by lncoll** [comment]
Just today found an image from an old US system.
It has WindowWidth and WindowCenter tags but empty.
So supose is better this:

```
  [[  
  local a=newdicomobject();  
  a:Read("]]..imagelocation..[[");  
  local c = (a.WindowCenter or 0)  
  local w = (a.WindowWidth or 0)  
  if (c==0 or w==0 or c=='' or w=='') then  
    b = (a.BitsStored or 11)  
    w = 2^b  
    c = w/2  
  end  
  local s = (a.RescaleSlope or 1)     if s=='' then s=1 end  
  local i = (a.RescaleIntercept or 0) if i=='' then i=0 end  
  return c.."|"..w.."|"..s.."|"..i  
  ]]  
```
BitsStored is not optional in a image, so think there is not need to check if empty.
No need of math.floor() for w/2 , a power of 2 is always even, ;p

Luis.

**Comment by marcelvanherk** [comment]
Hi Luis,

just updating it!

Marcel

**Comment by lncoll** [comment]
Tested for more than a week in 4 servers.
Seems to work ok.
Close the issue.

Thanks Marcel.
