### ISSUE TITLE
Webhooks for Modlity Worklist Server queries

### ISSUE THREAD

**Issue by aptvision-paulw** [marcelvanherk/Conquest-DICOM-Server#6]
Hi,

We'd like to have an ability to call an API to retrieve data from a third party system when a modality queries the modality worklist server (rather than using the database). 
We are happy to do the development required, would you consider accepting a pull request when this is ready and you are satisfied with the implementation?

I presume this would only require adding the necessary code to: https://github.com/marcelvanherk/Conquest-DICOM-Server/blob/d963df1b66270f89e86b28be121f7c0913479ec4/src/dgate/src/vrtosql.cpp#L2592 

Thanks

**Comment by marcelvanherk** [comment]
Hi,

I guess that the cleanest way to do this is to add a lua interface to
create the response and then build a lua plugin. But what method do you
have in mind? It must be generic enough to be in the main code. But of
course we can put it in an #ifdef block, happy to include it if it comes
with few dependencies.

regards,

Marcel

**Comment by marcelvanherk** [comment]
Closed because of lack of activity
