### ISSUE TITLE
Conquest with 32 bit Postgresql not working 

### ISSUE THREAD

**Issue by arunjoshtech** [marcelvanherk/Conquest-DICOM-Server#9]
I want to use conquest with postgresql in 32 Bit windows 7. Conquest with 64 bit Postgresql works fine but not work with 32 bit version of Postgresql. I tested older versions too.. Kindly help to resolve it

**Comment by marcelvanherk** [comment]
Hi,

as documented there are no 32 drivers bundled for postgres; you need to
manually copy these from your postgres install into the server folder.

Marcel

**Comment by marcelvanherk** [comment]
Closed - not a bug
